// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "infrastructure/database/prisma/schema",  // папка
  migrations: {
    path: "infrastructure/database/prisma/migrations",
  },
  datasource: {
    url: process.env.NODE_ENV === 'production'
      ? `${process.env.DATABASE_URL}?sslmode=require`
      : process.env.DATABASE_URL!,
  },
});
