// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from 'dotenv';
import { defineConfig } from "prisma/config";
dotenv.config();

export default defineConfig({
  schema: "infrastructure/database/prisma/schema",  // папка
  migrations: {
    path: "infrastructure/database/prisma/migrations",
  },
  datasource: {
    url: 'postgresql://postgres:12345@localhost:5432/Website'
  },
});
